version: '3.8'

services:
  backend:
    build:
      context: ./src/be
      dockerfile: Dockerfile
    container_name: finance-ai-backend
    environment:
      SECRET_KEY: "your-super-secret-key-change-in-production"
      DATABASE_URL: "sqlite:///:memory:"
    ports:
      - "8000:8000"
    networks:
      - finance-ai-network
    healthcheck:
      test: ["CMD", "python", "-c", "import httpx; httpx.get('http://localhost:8000/health')"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    restart: unless-stopped

  frontend:
    build:
      context: ./src/fe
      dockerfile: Dockerfile
    container_name: finance-ai-frontend
    ports:
      - "3000:80"
    depends_on:
      backend:
        condition: service_healthy
    networks:
      - finance-ai-network
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:80/health"]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 5s
    restart: unless-stopped

networks:
  finance-ai-network:
    driver: bridge

# volumes:
  # If you want to persist data, uncomment and use these volumes
  # backend_data:
  # frontend_data: 